[package]
name = "MicroDonationPlatform"
version = "1.0.0"
authors = []

[addresses]
MicroDonationPlatform='0xeebddaddd0a1da87cf221ff7c5bd78147035210614d73b0cb00d14f01d6476d4'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
